.github/CODEOWNERS

In order to add reviewers to pull requests review, we need to add DS core team in the CODEOWNERS file

chore(github): add CODEOWNERS file

---

packages/contributing/contributing-troubleshooting-notes.mdx
packages/contributing/howto/contributing-create-component.mdx

- add troubleshooting notes about yarn.lock file
- update doc to explain that components have to be added in Introduction and All components pages

feat/update doc 

---

packages/tools/storybook/stories/home.stories.mdx

Links were heading to wrong URLs on Home Storybook page

fix(storybook): wrong links on home page

---

packages/libraries/core/src/components/button/ods-button-attributes.ts
packages/libraries/core/src/components/button/ods-button-controller.spec.ts
packages/libraries/core/src/components/button/ods-button-controller.ts
packages/libraries/core/src/components/button/ods-button-default-attributes.ts
packages/libraries/core/src/components/button/ods-button-mock.ts
packages/libraries/core/src/components/ods-component-attributes-2-string-attributes.ts
packages/libraries/testing/src/components/button/ods-button-base-attributes.ts
packages/stencil/components/button/src/components/osds-button/osds-button.e2e.screenshot.ts
packages/stencil/components/button/src/components/osds-button/osds-button.e2e.ts
packages/stencil/components/button/src/components/osds-button/osds-button.spec.ts
packages/stencil/components/button/src/components/osds-button/osds-button.tsx
packages/stencil/components/button/src/components/osds-button/styles/osds-button.color.scss
packages/stencil/components/button/src/components/osds-button/styles/osds-button.size.scss
packages/stencil/components/button/src/docs/osds-button/properties/usage.circle.mdx
packages/stencil/components/button/src/docs/osds-button/usage.mdx
packages/stencil/components/button/src/global.dev.ts
packages/stencil/components/button/src/global.test.ts
packages/stencil/components/button/src/index.html
packages/stencil/components/button/stencil.config.ts
packages/stencil/components/text/src/components/osds-text/osds-text.spec.ts
packages/tools/storybook/stories/components/button/button.web-components.stories.ts

feat: add circle shape in button

---

packages/tools/generator/component/template/stencil/package.json
packages/tools/generator/component/template/stencil/react/package.json
packages/tools/generator/component/template/stencil/vue/package.json

Version in package.json file was not current one for generated components

fix(generator): generate good version

---

package.json
yarn.lock

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65501

fix: force @types/ws version

---

packages/tools/storybook/stories/components/accordion-group/accordion-group.web-components.stories.ts
packages/tools/storybook/stories/components/accordion/accordion.web-components.stories.ts
packages/tools/storybook/stories/components/button/button.web-components.stories.ts
packages/tools/storybook/stories/components/cart/cart.web-components.stories.ts
packages/tools/storybook/stories/components/checkbox-button/checkbox-button.web-components.stories.ts
packages/tools/storybook/stories/components/checkbox/checkbox.web-components.stories.ts
packages/tools/storybook/stories/components/chip/chip.web-components.stories.ts
packages/tools/storybook/stories/components/icon/icon.web-components.stories.ts
packages/tools/storybook/stories/components/input/input.web-components.stories.ts
packages/tools/storybook/stories/components/link/link.web-components.stories.ts
packages/tools/storybook/stories/components/location-tile/location-tile.web-components.stories.ts
packages/tools/storybook/stories/components/message/message.web-components.stories.ts
packages/tools/storybook/stories/components/pagination/pagination.web-components.stories.ts
packages/tools/storybook/stories/components/quantity/quantity.web-components.stories.ts
packages/tools/storybook/stories/components/radio-button/radio-button.web-components.stories.ts
packages/tools/storybook/stories/components/select/select.web-components.stories.ts
packages/tools/storybook/stories/components/textarea/textarea.web-components.stories.ts
packages/tools/storybook/stories/components/tile/tile.web-components.stories.ts
packages/tools/storybook/stories/components/toggle/toggle.web-components.stories.ts

docs(storybook): add Meta wrappers stories on Checkbox/Radio Buttons

---

packages/libraries/core/src/components/popover/popover/ods-popover-controller.ts
packages/stencil/components/popover/src/components/osds-popover/osds-popover.scss

fix(popover): rm setAnchorMargin & add inline-flex to trigger

---

packages-new/components/button/src/components/osds-button/core/controller.ts
packages-new/components/button/src/components/osds-button/osds-button.scss
packages-new/components/button/src/index.html

- fix vertical align on the center area. 
- I try with display: flex / grid but ellipsis not work with it
- Add example on the index.html
- Test disabled faibled. I change the controller for fix it

fix(button): vertical align + test disabled

---

packages-new/components/search-bar/src/index.html
packages-new/components/select/src/components/osds-select/osds-select.e2e.screenshot.ts
packages-new/components/select/src/components/osds-select/styles/osds-select.size.scss

Select Surface width can now adapt to its content and no longer the same size than the trigger

fix(select): surface width no longer the same than trigger

---

packages-new/components/radio/src/components/osds-radio/core/controller.ts

Fix undefined error in console for radio-group 
ODS-873

fix(radio-group): fix undefined error onDestroy

---

packages/components/checkbox-button/src/components/osds-checkbox-button/osds-checkbox-button.scss
packages/components/checkbox-button/src/components/osds-checkbox-button/styles/osds-checkbox-button.size.scss
packages/themes/blue-jeans/src/index.scss

ODS-876
Fix sizes of checkbox to include the border within

fix(checkbox-button): fix sizes of boxes

---

packages/components/skeleton/src/components/osds-skeleton/interfaces/attributes.ts
packages/components/skeleton/src/components/osds-skeleton/osds-skeleton.scss
packages/components/skeleton/src/components/osds-skeleton/osds-skeleton.tsx
packages/components/skeleton/src/index.html

- fix inline rendering
- fix size change
- fix local index.html
- update local examples to see non flex rendering

fix(skeleton): display size correctly when inline

---

packages/components/quantity/src/components/osds-quantity/osds-quantity.scss

Temporary fix to keep previous rendering.
Whole component will be refactored to replace the usage of slot with actual ods components

fix(quantity): set button width

---

packages/components/flag/src/docs/osds-flag/usage.mdx
packages/storybook/public/custom-flags/unia.svg
packages/storybook/public/flags/unia.svg

- fix the storybook errors on "Doc" tabs on flag Webcomponent story
- fix the display of flag on "Doc" tabs on flag Webcomponent story
- add missing unia flag

fix(flags): add missing unia && fix doc

---

packages/components/progress-bar/src/components/osds-progress-bar/interfaces/attributes.ts
packages/components/progress-bar/src/components/osds-progress-bar/osds-progress-bar.tsx

Does not make sense, plus controller code is actually wrong (testing value < 0 won't work correctly with string)

fix(progress-bar): allow only number for both attributes

---

packages/components/clipboard/stencil.config.ts
packages/components/input/package.json
packages/components/input/src/components/osds-input/constants/default-attributes.ts
packages/components/input/src/components/osds-input/interfaces/attributes.ts
packages/components/input/src/components/osds-input/osds-input.e2e.screenshot.ts
packages/components/input/src/components/osds-input/osds-input.spec.ts
packages/components/input/src/components/osds-input/osds-input.tsx
packages/components/input/src/components/osds-input/styles/osds-input.color.scss
packages/components/input/src/components/osds-input/styles/osds-input.typography.scss
packages/components/input/src/global.dev.ts
packages/components/input/src/global.test.ts
packages/components/input/src/index.html
packages/components/input/stencil.config.ts
packages/components/password/stencil.config.ts
packages/components/quantity/stencil.config.ts
packages/components/search-bar/stencil.config.ts
packages/storybook/stories/components/input/input.web-components.stories.ts
yarn.lock

Add prefixValue attribute 
The key prefix was reserved by stencil

feat(input): add prefix value

---

packages/components/select/src/components/osds-select-group/osds-select-group.e2e.screenshot.ts
packages/components/select/src/components/osds-select/osds-select.e2e.screenshot.ts

Test was missing an import, so failing all the times

fix(select): fix broken e2e screenshot tests

---

packages/components/phone-number/src/components/osds-phone-number/core/controller.ts
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.e2e.ts
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.scss
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.spec.ts
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.tsx
packages/components/select/src/components/osds-select/styles/osds-select.size.scss

- Style
- select sort
- filter country not supported by the `google-libphonenumber`

fix(phone-number): style select + clear input error + sort list select options

---

packages/storybook/stories/components/tile/tile.web-components.stories.ts

Attribute exposed on doc were not the same as actual tile attributes

fix(storybook): update tile attributes

---

packages/components/datagrid/src/components/osds-datagrid/constants/default-attributes.ts
packages/components/datagrid/src/components/osds-datagrid/core/controller.spec.ts
packages/components/datagrid/src/components/osds-datagrid/core/controller.ts
packages/components/datagrid/src/components/osds-datagrid/interfaces/attributes.ts
packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.e2e.ts
packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.spec.ts
packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.tsx
packages/components/datagrid/src/docs/osds-datagrid/usage.mdx
packages/components/datagrid/src/index.html
packages/storybook/stories/components/datagrid/datagrid.web-components.stories.ts

Add isSelectable & isSorbable by column

feat(datagrid): add more attributes

---

packages/components/text/src/components/osds-text/osds-text.spec.ts
packages/components/text/src/components/osds-text/osds-text.tsx

Add missing tests for full coverage of text

fix(text): add missing test line for coverage

---

packages/components/text/src/components/osds-text/osds-text.e2e.screenshot.ts

Change way of taking screenshot for one page only instead of multiples screenshots for each variations

feat(text): take all variations in one page screenshot only

---

packages/components/flag/src/components/osds-flag/constants/default-attributes.ts
packages/components/flag/src/components/osds-flag/constants/flag-iso-code.ts
packages/components/flag/src/components/osds-flag/core/controller.spec.ts
packages/components/flag/src/components/osds-flag/core/controller.ts
packages/components/flag/src/components/osds-flag/osds-flag.e2e.screenshot.ts
packages/components/flag/src/components/osds-flag/osds-flag.e2e.ts
packages/components/flag/src/components/osds-flag/osds-flag.scss
packages/components/flag/src/components/osds-flag/osds-flag.spec.ts
packages/components/flag/src/components/osds-flag/osds-flag.tsx

- style using BEM
- e2e screenshot on one page
Assets loading can not be change for now, so minimal clean-up

refactor(flag): clean up && put screenshot on one page

---

packages/components/tile/src/components/osds-tile/osds-tile.e2e.screenshot.ts

ODS-1021
Make screenshot of Tile cmpt in one page only

feat(tile): do screenshot in one page only

---

packages/components/quantity/src/components/osds-quantity/core/controller.spec.ts
packages/components/quantity/src/components/osds-quantity/core/controller.ts

ODS-784
Change value of quantity component to match steps

fix(quantity): change value onblur to be valid with step

---

packages/components/modal/src/components/osds-modal/interfaces/events.ts
packages/components/modal/src/components/osds-modal/osds-modal.e2e.ts
packages/components/modal/src/components/osds-modal/osds-modal.tsx

ODS-997
Add new event odsModalOpen and odsModalClose event for modal component

feat(modal): add event on open and close

---

packages/components/accordion/src/components/osds-accordion/core/controller.ts
packages/components/accordion/src/components/osds-accordion/osds-accordion.e2e.ts
packages/components/accordion/src/components/osds-accordion/osds-accordion.tsx
packages/storybook/stories/components/accordion/3_demo.stories.ts

- Fix accordion that was opening even when it was disabled

fix(accordion): dont open when disabled

---

packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.e2e.ts
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.tsx
packages/components/phone-number/src/index.html

odsValueChange was trigger on type in input and not juste when the value was valid

fix(phone-number): input event send when type on input

---

packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.e2e.ts
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.spec.ts
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.tsx
packages/components/phone-number/src/index.html

Trigger event odsValueChange everytime when type on the input

fix(phone-number): trigger event

---

packages/components/accordion/src/components/osds-accordion-group/core/controller.ts
packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.tsx
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.scss

Remove console.log
Set flag height & width the same

fix(phone-number): flag height

---

packages/components/datagrid/documentation/usage-guidelines/usage-style.css
packages/components/datagrid/documentation/usage-guidelines/usage.mdx
packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.e2e.ts
packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.tsx
packages/components/datagrid/src/index.html
packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.scss

Error on row change: test throx when the fix was not present
Phone-number / Search-bar select cropped

fix(datagrid): row change & storybook

---

packages/components/button/src/components/osds-button/osds-button.scss
packages/components/button/src/index.html

ODS-1122
Fix position of End slot when Start slot is empty in button

fix(button): fix position of end when there is no start slot

---

packages/components/phone-number/src/dev.ts
packages/components/phone-number/stencil.config.ts

ODS-1117
Fix error that did not show flag in the select while on local environnement

fix(phone): show flag on local env

---

packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.scss
packages/components/select/src/components/osds-select-option/osds-select-option.scss

ODS-1108
Fix shadow of flag icon in the select that was cut behind overflow

fix(phone-number): fix flag shadow in select

---

packages/components/pagination/src/components/osds-pagination/interfaces/events.ts
packages/components/pagination/src/components/osds-pagination/osds-pagination.e2e.ts
packages/components/pagination/src/components/osds-pagination/osds-pagination.spec.ts
packages/components/pagination/src/components/osds-pagination/osds-pagination.tsx

Add itemPerPage in payload event `odsPaginationChanged`
Watch totalPages & update it

fix(pagination): event payload & watch total pages

---

packages/components/src/modal/src/components/osds-modal/osds-modal.scss
packages/components/src/modal/src/globals.ts
packages/components/src/modal/src/index.html

ODS-1119
Change overflow of the content class to allow a better display when a surface is present in the modal

fix(modal): change overflow to allow ocdk-surface correct display

---

packages/components/src/tabs/documentation/usage-guidelines/usage.react.mdx
packages/components/src/tabs/src/components/osds-tab-bar-item/osds-tab-bar-item.scss

ODS-1031
Change margin to padding to allow the click on the whitespace between tabs

docs(tabs): change React doc with event handler & useNavigate hook

---

packages/components/src/button/src/components/osds-button/core/controller.ts
packages/components/src/button/src/components/osds-button/osds-button.e2e.ts
packages/components/src/button/src/components/osds-button/osds-button.tsx
packages/components/src/menu/src/components/osds-menu/core/controller.ts
packages/components/src/menu/src/components/osds-menu/osds-menu.tsx
packages/components/src/menu/src/index.html
packages/components/src/modal/src/components/osds-modal/osds-modal.tsx
packages/storybook/stories/components/modal/3_demo.stories.ts

Listen to Enter or Space on button and dispatch a click Event on it
Update Storybook to add close modal behaviour on cancel button

fix(modal): add key behaviour on storybook and close button

---

packages/components/src/modal/src/components/osds-modal/osds-modal.scss
packages/components/src/modal/src/components/osds-modal/osds-modal.tsx

Prevent scroll when modal is opened

fix(modal): prevent scroll when modal is open

---

packages/components/src/tile/src/components/osds-tile/osds-tile.scss

Fix border radius for tile on safari

fix(tile): rounded border on safari

---

packages/storybook/stories/components/radio-group/demo.stories.radio-button.ts
packages/storybook/stories/components/radio-group/demo.stories.update-strategy.ts
packages/storybook/stories/components/radio/demo.stories.update-strategy.ts

Fix console log in storybook for Update strategy Demo of Radio Group

fix(radio-group): fix log error in storybook

---

packages/common/theming/size/ods-theming-size.input.scss
packages/components/src/input/src/components/osds-input/osds-input.scss
packages/components/src/input/src/components/osds-input/styles/osds-input.size.scss
packages/themes/blue-jeans/src/index.scss

Fix input icon size using his own size instead of one setted for input component

fix(input): fix icon size

---

packages/components/src/tile/src/components/osds-tile/osds-tile.scss
packages/components/src/tile/src/components/osds-tile/osds-tile.tsx
packages/components/src/tile/src/index.html

Fix end slot position when there is no start slot in the tile

fix(tile): end slot position when there is no start slot

---

packages/components/src/modal/src/components/osds-modal/osds-modal.e2e.ts
packages/components/src/modal/src/components/osds-modal/osds-modal.tsx

fix(modal): close on disconnect

---

packages/components/src/modal/src/components/osds-modal/osds-modal.e2e.ts
packages/components/src/modal/src/components/osds-modal/osds-modal.tsx

closeModal event is called twice on unmount

fix(modal): closeModal event is called twice on unmount

---

packages/components/src/form-field/documentation/usage-guidelines/usage.mdx
packages/components/src/form-field/src/index.html
packages/components/src/input/documentation/usage-guidelines/usage.mdx
packages/components/src/textarea/documentation/usage-guidelines/usage.mdx

add accessibility using label and update storybook usage guidelines

docs(form-field): add accessibility using label and update storybook usage guidelines

---

packages/common/theming/size/ods-theming-size.textarea.scss
packages/components/src/textarea/src/components/osds-textarea/osds-textarea.scss
packages/components/src/textarea/src/components/osds-textarea/styles/osds-textarea.color.scss
packages/components/src/textarea/src/components/osds-textarea/styles/osds-textarea.size.scss
packages/components/src/textarea/src/components/osds-textarea/styles/osds-textarea.typography.scss
packages/themes/blue-jeans/src/index.scss

Change style of textarea to be more like input

fix(textarea): change style to be like osds-input

---

packages/components/src/modal/src/components/osds-modal/styles/osds-modal.size.scss

fix(modal): change width value on breakpoint

---

packages/components/src/datepicker/src/components/osds-datepicker/osds-datepicker.tsx

fix(datepicker): set days to 2 letters

---

packages/components/src/datepicker/src/components/osds-datepicker/styles/osds-datepicker.color.scss
packages/components/src/datepicker/src/index.html

Fix border color of datepicker surface when component is in error

fix(datepicker): surface border color in error

---

packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.ts
packages/components/src/pagination/src/components/osds-pagination/osds-pagination.tsx

Hide navigation of pagination when totalItems is lower than itemsPerPage

fix(pagination): hide navigation when totalitems lower itemsPerPage

---

packages/components/src/clipboard/src/components/osds-clipboard/core/controller.ts
packages/components/src/clipboard/src/components/osds-clipboard/osds-clipboard.e2e.ts
packages/components/src/clipboard/src/components/osds-clipboard/osds-clipboard.spec.ts
packages/components/src/clipboard/src/components/osds-clipboard/osds-clipboard.tsx
packages/components/src/clipboard/src/index.html

Adding a delay to close the surface tooltip and e2e test

fix(clipboard): fix tooltip close delay

---

packages/storybook/stories/components/content-addon/1_migration_.from.17.x.stories.mdx

Component will be removed in v18, so we just need some documentation about how to replace it.

feat(content-addon): add component migration doc

---

packages/components/src/clipboard/src/components/osds-clipboard/osds-clipboard.scss

Fix background color of surface in clipboard

fix(clipboard): fix surface background color

---

packages/ods/src/components/button/src/index.html
packages/ods/src/components/link/src/components/ods-link/ods-link.scss
packages/ods/src/components/link/src/components/ods-link/ods-link.tsx
packages/ods/src/components/link/src/index.html
packages/ods/src/style/_link.scss

- use icon font
- remove enforced ods font

fix(link): adapt icon style to icon font

---

packages/ods/react/tests/_app/src/components.ts
packages/ods/react/tests/_app/src/components/ods-divider.tsx
packages/ods/react/tests/e2e/ods-divider.e2e.ts
packages/ods/src/components/divider/.gitignore
packages/ods/src/components/divider/package.json
packages/ods/src/components/divider/src/components/ods-divider/ods-divider.scss
packages/ods/src/components/divider/src/components/ods-divider/ods-divider.tsx
packages/ods/src/components/divider/src/constants/divider-color.ts
packages/ods/src/components/divider/src/constants/divider-spacing.ts
packages/ods/src/components/divider/src/globals.ts
packages/ods/src/components/divider/src/index.html
packages/ods/src/components/divider/src/index.ts
packages/ods/src/components/divider/stencil.config.ts
packages/ods/src/components/divider/tests/rendering/ods-divider.e2e.ts
packages/ods/src/components/divider/tests/rendering/ods-divider.spec.ts
packages/ods/src/components/divider/tsconfig.json
packages/ods/src/components/divider/typedoc.json
packages/ods/src/components/index.ts
packages/ods/vue/tests/_app/src/components.ts
packages/ods/vue/tests/_app/src/components/ods-divider.vue
packages/ods/vue/tests/e2e/ods-divider.e2e.ts
packages/storybook/stories/components/divider/divider.stories.ts
packages/storybook/stories/components/divider/documentation.mdx
packages/storybook/stories/components/divider/migration.from.17.x.mdx
yarn.lock

Refactor component Divider
- contrasted, separator & size attributes removed
- new attribute spacing
- always show a visible separator now

feat(divider): implement component

---

packages/common/theming/size/ods-theming-size.radio-button.scss
packages/components/src/radio-button/src/components/osds-radio-button/constants/radio-button-size.ts
packages/themes/blue-jeans/src/index.scss

feat(radio-button): add xs size

---

packages/ods/react/tests/_app/src/components.ts
packages/ods/react/tests/_app/src/components/ods-form-field.tsx
packages/ods/react/tests/e2e/ods-form-field.e2e.ts
packages/ods/src/components/form-field/.gitignore
packages/ods/src/components/form-field/package.json
packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.scss
packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.tsx
packages/ods/src/components/form-field/src/globals.ts
packages/ods/src/components/form-field/src/index.html
packages/ods/src/components/form-field/src/index.ts
packages/ods/src/components/form-field/stencil.config.ts
packages/ods/src/components/form-field/tests/rendering/ods-form-field.e2e.ts
packages/ods/src/components/form-field/tests/rendering/ods-form-field.spec.ts
packages/ods/src/components/form-field/tsconfig.json
packages/ods/src/components/form-field/typedoc.json
packages/ods/src/components/index.ts
packages/ods/vue/tests/_app/src/components.ts
packages/ods/vue/tests/_app/src/components/ods-form-field.vue
packages/ods/vue/tests/e2e/ods-form-field.e2e.ts
packages/storybook/stories/components/form-field/documentation.mdx
packages/storybook/stories/components/form-field/form-field.stories.ts
packages/storybook/stories/components/form-field/migration.from.17.x.mdx
yarn.lock

feat(form-field): implement component

---

packages/ods/react/tests/_app/src/components.ts
packages/ods/react/tests/_app/src/components/ods-card.tsx
packages/ods/react/tests/e2e/ods-card.e2e.ts
packages/ods/src/components/card/.gitignore
packages/ods/src/components/card/package.json
packages/ods/src/components/card/src/components/ods-card/ods-card.scss
packages/ods/src/components/card/src/components/ods-card/ods-card.tsx
packages/ods/src/components/card/src/constants/card-color.ts
packages/ods/src/components/card/src/globals.ts
packages/ods/src/components/card/src/index.html
packages/ods/src/components/card/src/index.ts
packages/ods/src/components/card/stencil.config.ts
packages/ods/src/components/card/tests/rendering/ods-card.e2e.ts
packages/ods/src/components/card/tests/rendering/ods-card.spec.ts
packages/ods/src/components/card/tsconfig.json
packages/ods/src/components/card/typedoc.json
packages/ods/src/components/index.ts
packages/ods/vue/tests/_app/src/components.ts
packages/ods/vue/tests/_app/src/components/ods-card.vue
packages/ods/vue/tests/e2e/ods-card.e2e.ts
packages/storybook/stories/components/card/card.stories.ts
packages/storybook/stories/components/card/documentation.mdx
packages/storybook/stories/components/card/migration.from.17.x.mdx
packages/storybook/stories/zeroheight.ts
yarn.lock

> Card is a component designed to be a container for displaying content and other elements to communicate information or feature a call-to-action within a page.

feat(card): implement component

---

packages/ods/react/tests/_app/src/components.ts
packages/ods/react/tests/_app/src/components/ods-accordion.tsx
packages/ods/react/tests/e2e/ods-accordion.e2e.ts
packages/ods/src/components/accordion/.gitignore
packages/ods/src/components/accordion/package.json
packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.scss
packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.tsx
packages/ods/src/components/accordion/src/globals.ts
packages/ods/src/components/accordion/src/index.html
packages/ods/src/components/accordion/src/index.ts
packages/ods/src/components/accordion/stencil.config.ts
packages/ods/src/components/accordion/tests/navigation/ods-accordion.e2e.ts
packages/ods/src/components/accordion/tests/rendering/ods-accordion.e2e.ts
packages/ods/src/components/accordion/tests/rendering/ods-accordion.spec.ts
packages/ods/src/components/accordion/tsconfig.json
packages/ods/src/components/accordion/typedoc.json
packages/ods/src/components/index.ts
packages/ods/vue/tests/_app/src/components.ts
packages/ods/vue/tests/_app/src/components/ods-accordion.vue
packages/ods/vue/tests/e2e/ods-accordion.e2e.ts
packages/storybook/stories/components/accordion/accordion.stories.ts
packages/storybook/stories/components/accordion/documentation.mdx
packages/storybook/stories/components/accordion/migration.from.17.x.mdx
yarn.lock

> An Accordion is a vertical header that reveals or hides an associated section of content.

feat(accordion): implement component

---

packages/ods/src/style/_overlay.scss

Change fallback color from primary to text

fix(tooltip): change fallback color to text instead of primary

---

packages/ods/src/components/button/src/index.html
packages/ods/src/style/_button.scss

Set min width when the button has no label

fix(button): empty button min width

---

packages/ods/src/components/select/src/components/ods-select/ods-select.scss

Set color for selected option to primary-200

fix(select): set color for selected option

---

packages/examples/react-webpack/src/app/App.tsx
packages/examples/react-webpack/src/app/components/formFormik/FormFormik.tsx
packages/examples/react-webpack/src/app/components/formNative/FormNative.tsx
packages/ods/src/components/button/src/controller/ods-button.ts
packages/ods/src/components/button/src/index.html
packages/ods/src/components/button/tests/controller/ods-button.spec.ts

`form.requestSubmit` will submit the form from the button, thus triggering the form `onsubmit` handler

Fix button submit

---

packages/ods/src/components/pagination/src/components/ods-pagination/ods-pagination.tsx
packages/ods/src/components/pagination/src/index.html
packages/ods/src/components/pagination/tests/accessibility/ods-pagination.e2e.ts
packages/ods/src/components/pagination/tests/rendering/ods-pagination.e2e.ts

- Select is now always display
- There are not minimum page now

fix(pagination): always display number arrow and select

---

packages/ods/scripts/cem-enum-plugin.mjs
packages/ods/src/components/pagination/src/constants/pagination-per-page.ts
packages/storybook/src/components/technicalSpecification/TechnicalSpecification.tsx

- add a comment to prevent future self-questionning on pagination enum type
- add info on enum list to display differently number and string values

Pagination type

---

packages/examples/react-webpack/package.json
packages/examples/react-webpack/src/app/App.tsx
packages/examples/react-webpack/src/app/components/testSelect/TestSelect.tsx
packages/ods/src/components/phone-number/package.json
packages/ods/src/components/select/src/components/ods-select/ods-select.tsx
packages/ods/src/components/select/src/controller/ods-select.ts
packages/ods/src/components/select/src/index.html
packages/ods/src/components/select/tests/behaviour/ods-select.e2e.ts
packages/ods/src/components/select/tests/behaviour/ods-select.spec.ts
packages/ods/src/components/select/tests/rendering/ods-select.e2e.ts
packages/ods/src/components/select/tests/rendering/ods-select.spec.ts
packages/storybook/stories/ovhcloud-design-system/faq.mdx
yarn.lock

When slot change, creation of the select with tom select, the props isDisabled wasn't set on the tom select

fix(select): disabled on load select

---

packages/examples/react-webpack/src/app/App.tsx
packages/examples/react-webpack/src/app/components/formFormik/FormFormik.tsx
packages/examples/react-webpack/src/app/components/formHookForm/FormHookForm.tsx
packages/examples/react-webpack/src/app/components/formNative/FormNative.tsx
packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
packages/ods/src/components/range/src/index.html
packages/ods/src/components/range/tests/behaviour/ods-range.e2e.ts
packages/ods/src/components/range/tests/rendering/ods-range.spec.ts

Add range in the example
refactor changeValues and emit odsChange on input change

feat(range): add example

---

packages/ods/src/components/combobox/src/components/ods-combobox-group/ods-combobox-group.tsx
packages/ods/src/components/combobox/src/components/ods-combobox/ods-combobox.tsx
packages/ods/src/components/combobox/src/index.html
packages/ods/src/components/combobox/tests/rendering/ods-combobox.e2e.ts

fix(combobox): update onSlotChange to also reflect changes in the children

fix(combobox): update onSlotChange to also reflect changes in the children

---

packages/storybook/src/components/identityCard/IdentityCard.tsx
packages/storybook/stories/components/accordion/documentation.mdx
packages/storybook/stories/components/badge/documentation.mdx
packages/storybook/stories/components/breadcrumb/documentation.mdx
packages/storybook/stories/components/button/documentation.mdx
packages/storybook/stories/components/card/documentation.mdx
packages/storybook/stories/components/checkbox/documentation.mdx
packages/storybook/stories/components/clipboard/documentation.mdx
packages/storybook/stories/components/divider/documentation.mdx
packages/storybook/stories/components/form-field/documentation.mdx
packages/storybook/stories/components/icon/documentation.mdx
packages/storybook/stories/components/input/documentation.mdx
packages/storybook/stories/components/link/documentation.mdx
packages/storybook/stories/components/message/documentation.mdx
packages/storybook/stories/components/modal/documentation.mdx
packages/storybook/stories/components/password/documentation.mdx
packages/storybook/stories/components/popover/documentation.mdx
packages/storybook/stories/components/quantity/documentation.mdx
packages/storybook/stories/components/radio-group/documentation.mdx
packages/storybook/stories/components/select/documentation.mdx
packages/storybook/stories/components/skeleton/documentation.mdx
packages/storybook/stories/components/spinner/documentation.mdx
packages/storybook/stories/components/table/documentation.mdx
packages/storybook/stories/components/tabs/documentation.mdx
packages/storybook/stories/components/tag/documentation.mdx
packages/storybook/stories/components/text/documentation.mdx
packages/storybook/stories/components/textarea/documentation.mdx
packages/storybook/stories/components/tooltip/documentation.mdx

Anatomy img will be treated in a separated task

ods react doc for P1 & P2

---

packages/ods/src/components/pagination/src/components/ods-pagination/ods-pagination.tsx
packages/ods/src/components/pagination/src/controller/ods-pagination.ts
packages/ods/src/components/pagination/src/interfaces/pagination-page-list.ts
packages/ods/src/components/pagination/tests/controller/ods-pagination.spec.ts
packages/ods/src/components/pagination/tests/navigation/ods-pagination.e2e.ts
packages/ods/src/components/pagination/tests/rendering/ods-pagination.e2e.ts

From https://github.com/ovh/design-system/pull/797 
(We need a new branch to trigger CI/CD)

fix(pagination): handle large dataset

---

packages/ods-react/src/components/drawer/src/components/drawer-trigger/DrawerTrigger.tsx
packages/ods-react/src/components/modal/src/components/modal-trigger/ModalTrigger.tsx
packages/ods-react/src/components/popover/src/components/popover-trigger/PopoverTrigger.tsx
packages/ods-react/src/components/popover/src/components/popover/Popover.tsx
packages/ods-react/src/components/popover/src/contexts/usePopover.tsx
packages/ods-react/src/components/popover/src/dev.stories.tsx
packages/ods-react/src/components/tooltip/src/components/tooltip-trigger/TooltipTrigger.tsx
packages/ods-react/src/components/tooltip/src/components/tooltip/Tooltip.tsx
packages/ods-react/src/components/tooltip/src/contexts/useTooltip.tsx
packages/ods-react/src/components/tooltip/src/dev.stories.tsx
packages/storybook/stories/ovhcloud-design-system/faq.mdx

Issue only reproduced on Popover & Tooltip.
Drawer & Modal looks fine.

Fix overlay ids

---

packages/ods-react/package.json
packages/ods-react/src/components/file-upload/src/controller/file-upload.ts
yarn.lock

Revert https://github.com/ovh/design-system/pull/870 as lib changes to collection does impact our current combobox implementation (the "Add xxx" custom value leads to an empty input).
Bump will be put to test again after a fix is found.

fix(ods-react): revert to ark 5.12.0
