ovh/design-system

packages/tools/storybook/stories/components/button/button.web-components.stories.ts
In each Storybook stories, we need to have a single component to handle. 
On the Button story, there was specific cases displayed as well.
They need to be removed.
=> fix(button): remove extra buttons on Storybook story

packages/libraries/core/src/components/quantity/ods-quantity-behavior.ts, packages/libraries/core/src/components/quantity/ods-quantity-controller.spec.ts, packages/libraries/core/src/components/quantity/ods-quantity-controller.ts, packages/stencil/components/quantity/src/components/osds-quantity/osds-quantity.tsx
- init input in componentDidRender instead of connectedCallBack so type of osds-input is loaded at the proper moment
- remove unused event
- update controller test according to this change
=> fix(quantity): fix osds-input type in quantity

packages/libraries/cdk/package.json, packages/themes/blue-jeans/package.json, yarn.lock
`node-sass` cannot be installed on arm64 architecture unless it's version 8.
Seems there are no breaking changes, release notes only states change about Node version support being dropped.
=> fix(ods): set node-sass to v8 to avoid install issue with M1 mac

packages/tools/storybook/.storybook/main.js
In order to be linked with external tools, we need to add stories.json generation in Storybook configuration
=> chore(storybook): add stories.json

packages/libraries/core/src/components/input/ods-input-controller.ts, packages/stencil/components/input/src/components/osds-input/osds-input.e2e.ts, packages/stencil/components/input/src/components/osds-input/osds-input.scss, packages/stencil/components/input/src/components/osds-input/osds-input.spec.ts, packages/stencil/components/input/src/index.html
Inputs with clearable or passwords with masked were interactive if the input was disabled. This fix covers both cases, adds a specific cursor to the icons if the input is disabled and adds an e2e test to check if it works as intended.
=> fix(input): block actions if disabled

packages/tools/storybook/.storybook/get-docs-api-directories.js, packages/tools/storybook/.storybook/main.js
This fix the flags rendering, among other issues
=> fix(storybook): prevent static dir to be ignored on build

packages/components/datepicker/src/components/osds-datepicker/constants/default-attributes.ts, packages/components/datepicker/src/components/osds-datepicker/core/controller.ts, packages/components/datepicker/src/components/osds-datepicker/interfaces/attributes.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.e2e.screenshot.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.scss, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.spec.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.tsx, packages/components/datepicker/src/components/osds-datepicker/styles/osds-datepicker.color.scss, packages/components/datepicker/src/components/osds-datepicker/styles/osds-datepicker.size.scss, packages/components/datepicker/src/components/osds-datepicker/styles/osds-datepicker.typography.scss, packages/components/datepicker/src/global.dev.ts, packages/components/datepicker/src/global.test.ts, packages/components/datepicker/src/index.html, packages/components/package.json, packages/storybook/stories/components/datepicker/datepicker.web-components.stories.ts, yarn.lock
Datepicker component styling
2 new attributes:
> color?: defines the color of the Datepicker
> inline?: defines if the component should be inline
The datepicker module is displayed seamlessly border-to-border with the input above, input's bottom right corner radius is adjusted regarding the inline attribute.
=> feat(datepicker): step 2, styling the component

packages/components/textarea/documentation/specifications/spec.md, packages/components/textarea/src/components/osds-textarea/core/controller.ts, packages/components/textarea/src/components/osds-textarea/interfaces/events.ts, packages/components/textarea/src/components/osds-textarea/osds-textarea.e2e.ts, packages/components/textarea/src/components/osds-textarea/osds-textarea.tsx
Fixing problem with Textarea component.
Event `odsValueChange` was not triggered and overall `value` was not updated on user input because of wrong data validation.
You can reproduce the issue by watching `odsValueChange` and typing inside the `textarea`. `odsValueChange` will only be triggered on `clear` or if `value` is equal to `''`.
The reason this problem bypassed the tests is `odsValueChange`'s emit was only tested on literal change of value, and not on reproducing the manual input behavior, hence the new test I added.
=> fix(textarea): emit odsValueChange on value change

packages/components/datepicker/src/components/osds-datepicker/constants/datepicker-day.ts, packages/components/datepicker/src/components/osds-datepicker/constants/default-attributes.ts, packages/components/datepicker/src/components/osds-datepicker/core/controller.ts, packages/components/datepicker/src/components/osds-datepicker/interfaces/attributes.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.e2e.screenshot.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.e2e.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.scss, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.tsx, packages/components/datepicker/src/index.html, packages/storybook/stories/components/datepicker/datepicker.web-components.stories.ts
Adding options to disable specific dates of the Datepicker.
New enum: 
`ODS_DATEPICKER_DAY`: monday = 1, saturday = 6, etc.
New attributes:
> datesDisabled?: Date[] (specific dates to disable)
> daysOfWeekDisabled?: ODS_DATEPICKER_DAY[] (ex: monday, sunday disabled for all dates)
> maxDate?: Date (maximum date selectable)
> minDate?: Date (minimum date selectable)
=> feat(datepicker): step 3, excluding dates

packages/cdk/dev/src/components/surface/ocdk-surface-basic-example/ocdk-surface-basic-position.ts, packages/cdk/dev/src/components/surface/ocdk-surface-tooltip-example/ocdk-surface-tooltip-example.tsx, packages/cdk/dev/src/components/surface/ocdk-surface-tooltip-example/ocdk-surface-tooltip-position.ts, packages/cdk/dev/src/index.html, packages/cdk/dev/src/www.ts, packages/cdk/src/components/surface/core/ocdk-surface-corner.ts, packages/cdk/src/components/surface/core/ocdk-surface-normalized-corner.ts, packages/cdk/src/components/surface/strategies/symmetry/ocdk-surface-symmetry-strategy.ts, packages/cdk/src/components/surface/strategies/symmetry/ocdk-surface-symmetry.cl-cr.ts, packages/cdk/src/components/surface/strategies/symmetry/ocdk-surface-symmetry.cr-cl.ts, packages/components/clipboard/package.json, packages/components/clipboard/src/components/osds-clipboard/core/controller.spec.ts, packages/components/clipboard/src/components/osds-clipboard/core/controller.ts, packages/components/clipboard/src/components/osds-clipboard/interfaces/methods.ts, packages/components/clipboard/src/components/osds-clipboard/osds-clipboard.e2e.ts, packages/components/clipboard/src/components/osds-clipboard/osds-clipboard.scss, packages/components/clipboard/src/components/osds-clipboard/osds-clipboard.spec.ts, packages/components/clipboard/src/components/osds-clipboard/osds-clipboard.tsx, packages/components/clipboard/src/components/osds-clipboard/public-api.ts, packages/components/clipboard/src/index.html, packages/storybook/stories/components/clipboard/clipboard.web-components.stories.ts, yarn.lock
ODS-613
- Add 2 slot to handle confirmation message
- Add surface to show the confirmation message as tooltip
=> feat(clipboard): add tooltip message for confirmation

packages/components/datepicker/package.json, packages/components/datepicker/src/components/osds-datepicker/core/controller.ts, packages/components/datepicker/src/components/osds-datepicker/interfaces/events.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.spec.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.tsx, packages/components/datepicker/src/components/osds-datepicker/public-api.ts, packages/components/datepicker/src/jestStub.js, tsconfig.json
> Adding exports for `odsDatepickerValueChange`, `odsDatepickerValueChangeEventDetail`, `ODS_DATEPICKER_DAY` & `ODS_DATEPICKER_DAYS` inside `public-api.ts`
> Adding `build:ci` command
> Adding `formattedValue` inside `odsDatepickerValueChange` event.
=> fix(datepicker): fix exports

packages/components/modal/src/components/osds-modal/osds-modal.e2e.ts, packages/components/modal/src/components/osds-modal/osds-modal.tsx
Fixed end-to-end tests for modal component:
- trigger inert at modal open (masked is false on component create and masked is also false on open, so it did not trigger the inert watcher)
- fix e2e test by adding open to the test for inert attribute
=> fix(modal): trigger inert at modal open and fix e2e test

packages/components/clipboard/documentation/specifications/spec.md, packages/components/datepicker/documentation/specifications/spec.md, packages/components/datepicker/src/components/osds-datepicker/constants/datepicker-locale.ts, packages/components/datepicker/src/components/osds-datepicker/constants/default-attributes.ts, packages/components/datepicker/src/components/osds-datepicker/interfaces/attributes.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.e2e.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.spec.ts, packages/components/datepicker/src/components/osds-datepicker/osds-datepicker.tsx, packages/components/datepicker/src/components/osds-datepicker/public-api.ts, packages/components/datepicker/src/index.html, packages/components/datepicker/src/jestStub.js, packages/components/text/documentation/specifications/spec.md, packages/storybook/stories/components/datepicker/datepicker.web-components.stories.ts
Add a `locale` option to datepicker.
The list of locales imported match the user needs for now.
If more locale are needed, more import should be added to the component accordingly.
=> feat(datepicker): add locale prop

packages/components/select/src/components/osds-select-option/osds-select-option.tsx, packages/components/select/src/components/osds-select/osds-select.e2e.ts, packages/components/select/src/components/osds-select/osds-select.spec.ts, packages/components/select/src/components/osds-select/osds-select.tsx, packages/components/select/src/global.dev.ts
Fix: select-option content change but the label of a selected value don't change.
- no fix with the slot `selectedLabel` because it's up to the client to change the slot
- event `onSlotChange` don't work when just the text change
=> fix(select): change label on slot change

packages/components/popover/src/components/osds-popover/core/controller.ts, packages/components/popover/src/components/osds-popover/osds-popover.tsx
Popover does not work on a React App.
Removing the lifecycle code (which is useless btw) fixes the issue.
=> fix(popover): remove useless code in lifecycle

packages/components/menu/src/components/osds-menu/core/controller.spec.ts, packages/components/menu/src/components/osds-menu/core/controller.ts, packages/components/menu/src/components/osds-menu/osds-menu.tsx
A bit of cleaning and reordering, but the main issue was from:
```
title: HTMLElement | null = null;
```
which was causing React component to fail due to unallowed DOM operation. Seems like the `= null` initializer is causing the issue.
I've replaced it with a dynamic getter as the previous code was causing other issues.
=> fix(menu): replace initialized element with getter

packages/storybook/stories/components/menu/menu.web-components.stories.ts
Fixing menu component story by removing text items from slots and adding start text-align property on parent button.
Usage documentation to be updated later (👀 @astagnol)
=> fix(menu): fixing story

packages/components/flag/src/components/osds-flag/osds-flag.scss
📐 Fixing display on Safari browser by adding default width and height
=> fix(flag): fixing display on Safari browser by adding default width and height

packages/components/select/src/components/osds-select/core/controller.ts
ODS-771
When on first option, shift + tab now focused the trigger and don't stay on first option anymore
=> fix(select): shift tab now focus trigger on first

packages/components/select/src/components/osds-select/osds-select.tsx, packages/components/select/src/dev.ts
Not work juste with `childList`, test e2e ok but not work on React App without the fix.
I try on a React App :
```
const App = () => {
const [list, setList] = useState([
{ value: "1", label: "1" },
{ value: "2", label: "2" },
{ value: "3", label: "3" },
])
function update() {
setList(list.map(item => ({ ...item, label: item.label + 'test'})));
}
return (
<div>
<OsdsSelect>
{ list.map((item) => <OsdsSelectOption key={item.value} value={item.value} >{item.label}</OsdsSelectOption>) }
</OsdsSelect>
<button onClick={() => update()}>test</button>
</div>
)
}
```
=> fix(select): observable for label change

packages/components/modal/src/components/osds-modal/constants/default-attributes.ts, packages/components/modal/src/components/osds-modal/interfaces/events.ts, packages/components/modal/src/components/osds-modal/interfaces/methods.ts, packages/components/modal/src/components/osds-modal/osds-modal.e2e.screenshot.ts, packages/components/modal/src/components/osds-modal/osds-modal.e2e.ts, packages/components/modal/src/components/osds-modal/osds-modal.scss, packages/components/modal/src/components/osds-modal/osds-modal.spec.ts, packages/components/modal/src/components/osds-modal/osds-modal.tsx, packages/components/modal/src/components/osds-modal/styles/osds-modal.color.scss, packages/components/modal/src/components/osds-modal/styles/osds-modal.size.scss, packages/components/modal/src/index.html
- `OsdsModal` is now using a `HTMLDialogElement` and is no longer appended to the body. (_fixes react children problem)_
- `OsdsModal` is now reactive to `Escape` key. _(will close the modal if dismissible)_
- `OsdsModal`'s icon has been fixed and no longer features a colored background.
- Tests have been added to check if focus is well applied.
=> fix(modal): switch to dialog element

packages/components/datagrid/documentation/usage-guidelines/usage-style.css, packages/components/datagrid/documentation/usage-guidelines/usage.mdx, packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.e2e.screenshot.ts, packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.e2e.ts, packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.scss, packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.spec.ts, packages/components/datagrid/src/index.html, packages/storybook/stories/components/datagrid/4_demo.stories.ts
If the `OsdsDatagrid` contains an overflowing on-interaction element (such as `OsdsMenu`, `OsdsTooltip`, `OsdsSelect` or `OsdsPopover`), the element is either being displayed at the top left corner of the `OsdsDatagrid` _(native)_ or beneath the element, making it `unvisible` _(React)_.
This fix intends to correct this problem in both environments.
=> fix(datagrid): overflowing elements are cut off

packages/common/core/src/version.ts
Now in the navigator `window.ods.version` is the current version
The script `yarn build:prod` also run `./scripts/generate-ods-version.js` and this script update the version in the dist files `/version`
=> fix(core): config version

packages/components/src/menu/documentation/usage-guidelines/usage.mdx, packages/storybook/stories/components/menu/3_demo.stories.ts
Updated Usage Guidelines for Menu (items content should not be in start & end slots)
=> fix(doc): rm useless slotting in menu usage

packages/components/src/datagrid/documentation/usage-guidelines/usage-react.mdx
- This update intends to fix `ReactDOM.render is no longer supported in React 18` error that was displayed several times while initiating the `OsdsDatagrid` component in React.
- The new documentation for React now uses `createRoot` which is encouraged in React 18.
- Other errors / logs supposedly covered by this branch were due to wrong usage.
=> docs(datagrid): update reactFormatter to fit React 18

packages/components/src/datagrid/documentation/specifications/spec.md, packages/components/src/pagination/documentation/specifications/spec.md, packages/components/src/pagination/src/components/osds-pagination/interfaces/events.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.spec.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.tsx, packages/components/src/pagination/src/components/osds-pagination/public-api.ts, packages/components/src/pagination/src/index.html, packages/components/src/skeleton/documentation/specifications/spec.md
Trigger a `odsPaginationItemPerPageChanged` event on `itemPerPage` select change, with the following payload:
```
current: 10 // new select value
currentPage: 1 // new page after change
totalPages: 6 // new number of pages after change
```
This replace the ods event triggered by the internal `ods-select` component
=> feat(pagination): add odsPaginationItemPerPageChanged on itemPerPage change

packages/components/src/pagination/package.json, packages/components/src/pagination/src/components/osds-pagination/core/controller.spec.ts, packages/components/src/pagination/src/components/osds-pagination/core/controller.ts, packages/components/src/pagination/src/components/osds-pagination/interfaces/attributes.ts, packages/components/src/pagination/src/components/osds-pagination/interfaces/events.ts, packages/components/src/pagination/src/components/osds-pagination/interfaces/methods.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.screenshot.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.spec.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.tsx
**Bug Description:** Pagination - Goes out of bounds _[Chromium, Safari]_
**Steps to verify:** 
1) Open `OsdsPagination` component on `Chromium` or `Safari`.
2) Click on disabled `previous` arrow or `next` arrow.
3) The component should not go out of bounds anymore.
=> fix(pagination): Component goes out of bounds

packages/components/src/modal/package.json, packages/components/src/modal/src/components/osds-modal/interfaces/attributes.ts, packages/components/src/modal/src/components/osds-modal/osds-modal.e2e.screenshot.ts, packages/components/src/modal/src/components/osds-modal/osds-modal.e2e.ts, packages/components/src/modal/src/components/osds-modal/osds-modal.scss, packages/components/src/modal/src/components/osds-modal/osds-modal.spec.ts, packages/components/src/modal/src/components/osds-modal/osds-modal.tsx, packages/components/src/modal/src/components/osds-modal/styles/osds-modal.size.scss, packages/components/src/modal/src/globals.ts, packages/components/src/modal/src/index.html
Content:
- Fixing display problems within the modal that could lead to some elements getting shrunk.
- `max-height` of `OsdsModal`'s content has been raised to `50vh`.
- TS Linters have been fixed.
To review:
Check files `osds-modal.scss` and `osds-modal.size.scss` to review the **main** fix.
Check the other files to review **linters** fix.
To reproduce & compare the initial bug:
Add a lot of content inside an `OsdsModal` so that it becomes scrollable and add a few `OsdsInput` to see how they get truncated.
=> fix(modal): elements get truncated

packages/components/src/input/src/components/osds-input/osds-input.scss
Fix input type number showing arrow in Safari and chromium
=> fix(quantity): fix arrow showing in safari

packages/components/src/components.d.ts, packages/components/src/pagination/documentation/specifications/spec.md, packages/components/src/pagination/src/components/osds-pagination/constants/default-attributes.ts, packages/components/src/pagination/src/components/osds-pagination/core/controller.spec.ts, packages/components/src/pagination/src/components/osds-pagination/interfaces/attributes.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.screenshot.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.spec.ts, packages/components/src/pagination/src/components/osds-pagination/osds-pagination.tsx, packages/components/src/pagination/src/index.html, packages/storybook/stories/components/pagination/3_demo.stories.ts
This new feature will allow the users to set a default page in the `OsdsPagination` component with the new `defaultCurrentPage` attribute.
---
- Added new attribute `defaultCurrentPage` to `OsdsPagination`.
- Added new method `getCurrentPage()`.
- Removed old attribute `current`.
- Updated documentation
- Updated spec, e2e & screenshot tests
- Updated Storybook
---
Check if you can set a `defaultCurrentPage` attribute to the `OsdsPagination` component and if it is well displayed and still allows for interaction with the component.
=> feat(pagination): add defaultCurrentPage attribute, remove current & update tests

packages/components/src/modal/src/components/osds-modal/osds-modal.e2e.ts, packages/components/src/modal/src/components/osds-modal/osds-modal.scss, packages/components/src/modal/src/components/osds-modal/osds-modal.tsx, packages/components/src/modal/src/components/osds-modal/styles/osds-modal.color.scss, packages/components/src/modal/src/components/osds-modal/styles/osds-modal.size.scss, packages/components/src/modal/src/index.html, packages/components/src/popover/src/components/osds-popover/styles/osds-popover.size.scss, packages/components/src/select/src/components/osds-select/osds-select.tsx
If an `OcdkSurface` is contained into a `OsdsPopover` or `OsdsModal` component and is too large for its container, it will be overflowing inside the said container leading to an unpleasant scroll both horizontally and vertically.
- Fixing the issue on `OsdsPopover` by adding overflow properties.
- Fixing the issue on `OsdsModal` by editing the structure of the component and its SCSS properties.
- Fixing the issue with the `OsdsModal` if you open an `OsdsSelect` inside and close it with the `ESC` key.
Check if the listed fixes above work on every testable environment you have. Make sure that the Surface will overflow from the `OsdsModal` or the `OsdsPopover` when it should.
=> fix(modal/popover): Overflowing Surfaces

packages/components/src/menu/src/components/osds-menu/styles/osds-menu.size.scss
Fix bottom margin when there is one element by setting min height in menu style instead of automatically setted by CDK
=> fix(menu): force min height in style instead of CDK

packages/components/src/autocomplete/src/components/osds-autocomplete/constants/default-attributes.ts, packages/components/src/autocomplete/src/components/osds-autocomplete/interfaces/attributes.ts, packages/components/src/autocomplete/src/components/osds-autocomplete/osds-autocomplete.e2e.screenshot.ts, packages/components/src/autocomplete/src/components/osds-autocomplete/osds-autocomplete.e2e.ts, packages/components/src/autocomplete/src/components/osds-autocomplete/osds-autocomplete.scss, packages/components/src/autocomplete/src/components/osds-autocomplete/osds-autocomplete.spec.ts, packages/components/src/autocomplete/src/components/osds-autocomplete/osds-autocomplete.tsx, packages/components/src/autocomplete/src/globals.ts, packages/components/src/autocomplete/src/index.html, packages/storybook/stories/components/autocomplete/3_demo.stories.ts
`OsdsAutocomplete` is a new component that allows users to type into an input that will open a dropdown displaying a list of selectable options from which the user can choose from.
This addition allows users to add an `isLoading` attribute to the component.
- `isLoading` will display an `OsdsSpinner` inside the Autocomplete component instead of the slot for the options.
Check if the `isLoading` attribute works and reacts properly with the correct styling.
=> feat(autocomplete): loading state

packages/ods/src/components/link/src/components/ods-link/ods-link.tsx, packages/ods/src/components/link/src/index.html, packages/ods/src/components/link/tests/navigation/ods-link.e2e.ts, packages/ods/src/components/link/tests/rendering/ods-link.e2e.ts, packages/ods/src/components/link/tests/rendering/ods-link.spec.ts, packages/storybook/stories/components/link/link.stories.ts, packages/storybook/stories/components/link/migration.from.17.x.mdx
As discused, all boolean prop will follow a specific naming convention (`isProp`, `hasProp`, `withProp`)
=> refactor(link): normalize boolean prop naming

packages/ods/react/tests/_app/src/components.ts, packages/ods/react/tests/_app/src/components/ods-code.tsx, packages/ods/react/tests/e2e/ods-code.e2e.ts, packages/ods/src/components/code/.gitignore, packages/ods/src/components/code/package.json, packages/ods/src/components/code/src/components/ods-code/ods-code.scss, packages/ods/src/components/code/src/components/ods-code/ods-code.tsx, packages/ods/src/components/code/src/globals.ts, packages/ods/src/components/code/src/index.html, packages/ods/src/components/code/src/index.ts, packages/ods/src/components/code/stencil.config.ts, packages/ods/src/components/code/tests/behaviour/ods-code.e2e.ts, packages/ods/src/components/code/tests/navigation/ods-code.e2e.ts, packages/ods/src/components/code/tests/rendering/ods-code.e2e.ts, packages/ods/src/components/code/tests/rendering/ods-code.spec.ts, packages/ods/src/components/code/tsconfig.json, packages/ods/src/components/code/typedoc.json, packages/ods/src/components/index.ts, packages/ods/vue/tests/_app/src/components.ts, packages/ods/vue/tests/_app/src/components/ods-code.vue, packages/ods/vue/tests/e2e/ods-code.e2e.ts, packages/storybook/stories/components/clipboard/clipboard.stories.ts, packages/storybook/stories/components/code/code.stories.ts, packages/storybook/stories/components/code/documentation.mdx, packages/storybook/stories/components/code/migration.from.17.x.mdx, yarn.lock
As there are no specific designs for this component, I went with the simpliest version, which is the same as the actual.
Which means no toolip on copy button (unlike clipboard), could be added on another iteration if actually asked for.
=> feat(code): implement component

packages/storybook/stories/components/badge/documentation.mdx, packages/storybook/stories/components/breadcrumb/documentation.mdx, packages/storybook/stories/components/button/documentation.mdx, packages/storybook/stories/components/clipboard/documentation.mdx, packages/storybook/stories/components/code/documentation.mdx, packages/storybook/stories/components/divider/documentation.mdx, packages/storybook/stories/components/icon/documentation.mdx, packages/storybook/stories/components/input/documentation.mdx, packages/storybook/stories/components/link/documentation.mdx, packages/storybook/stories/components/medium/documentation.mdx, packages/storybook/stories/components/password/documentation.mdx, packages/storybook/stories/components/popover/documentation.mdx, packages/storybook/stories/components/quantity/documentation.mdx, packages/storybook/stories/components/skeleton/documentation.mdx, packages/storybook/stories/components/spinner/documentation.mdx, packages/storybook/stories/components/table/documentation.mdx, packages/storybook/stories/components/tag/documentation.mdx, packages/storybook/stories/components/text/documentation.mdx, packages/storybook/stories/components/textarea/documentation.mdx, packages/storybook/stories/components/toggle/documentation.mdx, packages/storybook/stories/components/tooltip/documentation.mdx, packages/storybook/stories/doc-navigator.tsx, scripts/component-generator/templates/storybook/documentation.mdx.hbs
Components with composed names _(eg: Form Field, Progress Bar)_ were not taken in charge in the current doc-navigator system, leading to issues with the generated zeroheight link in the Documentation.
- Updated `doc-navigator.tsx` to accept a `linkId` property, based on the `zeroheight.ts` enum, removed unused code.
- Updated all existing components with the new system.
- Updated the `component-generator` to fit with the new code. 
Check if the component links are well connected to the proper zeroheight. Look for any discrepancies in the code. Check if the new component-generator works properly.
=> fix(doc): Handle composed names for Zeroheight links

packages/components/src/button/src/components/osds-button/core/controller.ts, packages/components/src/button/src/components/osds-button/osds-button.scss, packages/components/src/button/src/components/osds-button/osds-button.spec.ts, packages/components/src/button/src/components/osds-button/osds-button.tsx, packages/components/src/button/src/index.html, packages/examples/react-webpack/src/app/App.tsx
Remove margin & padding to prevent click event outside of the component
=> fix(button): remove margin & padding of host

packages/storybook/stories/components/content-addon/migration.from.17.x.mdx, packages/storybook/stories/components/menu/migration.from.17.x.mdx, packages/storybook/stories/components/popover/documentation.mdx, packages/storybook/stories/components/popover/popover.stories.ts
Component will be removed in v18, so some documentation has been added about how to do an action menu using ods-popover .
Documentation added:
- in Menu migration guide
- in Popover documentation: "Popover as Action Menu"
A link to this documentation should be added later in FAQ
=> feat(menu): add component migration doc

packages/storybook/stories/components/tooltip/tooltip.stories.ts
Tooltip example is now centred correctly
=> fix(tooltip): fix examples & demo alignment

packages/storybook/stories/components/search-bar/migration.from.17.x.mdx
TBD the example uses two props from the Select that we did remove of the documentation (`border-rounded` and `dropdown-width`) as they were quite a patch due to the lack of easy style customization on select component.
But if we mention them here, we'll have to expose them in the Select documentation page also.
=> feat(doc): add search-bar migration doc

packages/examples/react-webpack/src/app/App.tsx, packages/examples/react-webpack/src/app/components/formNative/FormNative.tsx, packages/ods/src/components/timepicker/src/components/ods-timepicker/ods-timepicker.scss, packages/ods/src/components/timepicker/src/components/ods-timepicker/ods-timepicker.tsx, packages/ods/src/components/timepicker/src/constant/timezone-preset.ts, packages/ods/src/components/timepicker/src/controller/ods-timepicker.ts, packages/ods/src/components/timepicker/src/index.html, packages/ods/src/components/timepicker/tests/behavior/ods-timepicker.e2e.ts, packages/ods/src/components/timepicker/tests/controller/ods-timepicker.spec.ts, packages/ods/src/components/timepicker/tests/rendering/ods-timepicker.e2e.ts, packages/storybook/stories/components/phone-number/phone-number.stories.ts, packages/storybook/stories/components/timepicker/technical-information.mdx, packages/storybook/stories/components/timepicker/timepicker.stories.ts
- prevent displaying the timezone select if only the `currentTimezone` prop is set
- remove the Demo Timezone page, replaced by a toggle control on Demo page
=> Fix timezone doc

packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.scss, packages/ods/src/components/accordion/src/index.html
Stretch the summary slot wrapper to allow custom display, for example a display grid before:
after:
=> fix(accordion): update summary style

packages/ods/src/components/phone-number/src/controller/ods-phone-number.ts, packages/ods/src/components/phone-number/tests/controller/ods-phone-number.spec.ts, packages/storybook/stories/components/phone-number/documentation.mdx
To check the fallback to 'en' you'll need to have:
* no locale or wrong locale
* AND browser's locale not recognized (not managed by ODS)
=> feat(phone-number): set locale fallback to english

packages/storybook/assets/css/preview.css
We need to set this line-height on Breadcrumb component so, we avoid component style to be overridden by generic style (Storybook)
=> fix(breadcrumb): set line-height on breadcrumb

packages/ods/src/components/input/src/components/ods-input/ods-input.tsx, packages/ods/src/components/input/src/index.html, packages/ods/src/components/phone-number/src/components/ods-phone-number/ods-phone-number.tsx, packages/ods/src/components/phone-number/src/controller/ods-phone-number.ts, packages/ods/src/components/phone-number/src/index.html, packages/ods/src/components/phone-number/tests/behaviour/ods-phone-number.e2e.ts, packages/ods/src/components/phone-number/tests/controller/ods-phone-number.spec.ts, packages/ods/src/components/phone-number/tests/rendering/ods-phone-number.e2e.ts, packages/ods/src/components/phone-number/tests/rendering/ods-phone-number.spec.ts, packages/ods/src/components/phone-number/tests/validity/ods-phone-number.e2e.ts, packages/ods/src/utils/dom.ts, packages/ods/tests/utils/dom.spec.ts, packages/storybook/stories/components/phone-number/phone-number.stories.ts, packages/storybook/stories/components/textarea/textarea.stories.ts
- rewrite phone-number to use setCustomValidity instead of managing our own validityState object
- remove all observer/watcher on value, as odsChange event are received on every value change
- add a `customValidityMessage` prop to allow user to translated native form popup message
=> Form validity phone number

packages/storybook/scripts/generate-version-list.js
When releasing, version list was incomplete and we were forced to fix gh-pages branch each time (ex: https://github.com/ovh/design-system/commit/0f6eb2b1884ea26f16027f82ad1356fd3f9e8819)
This should add correctly the new version to the bundle published on npm.
=> fix(build): ensure lib new version is added to the bundled documentation

packages/examples/react-webpack/src/app/App.tsx, packages/examples/react-webpack/src/app/components/testModal/TestModal.tsx, packages/examples/vanilla-webpack/src/index.html, packages/ods/package.json, packages/ods/src/components/modal/src/components/ods-modal/ods-modal.tsx, packages/ods/src/components/popover/custom-elements-manifest.config.mjs, packages/ods/src/components/popover/src/components/ods-popover/ods-popover.scss, packages/ods/src/components/popover/src/components/ods-popover/ods-popover.tsx, packages/ods/src/components/popover/src/constants/popover-strategy.ts, packages/ods/src/components/popover/src/globals.ts, packages/ods/src/components/popover/src/index.html, packages/ods/src/components/popover/src/index.ts, packages/ods/src/components/popover/tests/rendering/ods-popover.e2e.ts, packages/ods/src/components/popover/tests/rendering/ods-popover.spec.ts, packages/ods/src/components/tooltip/custom-elements-manifest.config.mjs, packages/ods/src/components/tooltip/src/components/ods-tooltip/ods-tooltip.scss, packages/ods/src/components/tooltip/src/components/ods-tooltip/ods-tooltip.tsx, packages/ods/src/components/tooltip/src/constants/tooltip-strategy.ts, packages/ods/src/components/tooltip/src/globals.ts, packages/ods/src/components/tooltip/src/index.html, packages/ods/src/components/tooltip/src/index.ts, packages/ods/src/components/tooltip/tests/rendering/ods-tooltip.e2e.ts, packages/ods/src/components/tooltip/tests/rendering/ods-tooltip.spec.ts, packages/ods/src/utils/overlay.ts, packages/ods/tests/utils/overlay.spec.ts, packages/storybook/stories/components/popover/popover.stories.ts, packages/storybook/stories/components/popover/technical-information.mdx, packages/storybook/stories/components/tooltip/technical-information.mdx, packages/storybook/stories/components/tooltip/tooltip.stories.ts, yarn.lock
- add a strategy prop to tooltip & popover
This fixes overlay not positioned correctly when set in an ods-modal
- wrap the modal content slot
This prevents slotted elements to be impacted by the flex container style. This was an issue for example when setting just an icon with a tooltip in the slot, the icon will be rendered on the right, but its width will actually be 100% (due to parent flex), so the tooltip will be positioned in the middle of the modal instead of top of the icon.
=> Fix overlay in fixed context

packages/ods/src/components/switch/package.json
Small hack to separate switch test suites from the global one as it fails randomly when run with the rest.
CI pipeline has been updated to run `test:e2e:switch` after `test:e2e:ci`
=> fix(switch): use separate command to run e2e tests on CI

packages/ods/src/components/quantity/src/components/ods-quantity/ods-quantity.tsx, packages/ods/src/components/quantity/tests/navigation/ods-quantity.e2e.ts, packages/ods/src/components/quantity/tests/rendering/ods-quantity.e2e.ts
Update error state on blur with the increment & decrement button
One deletions is required for emptying the input instead of 2
=> fix(quantity): error state & double deletions for emptying input

packages/storybook/src/components/heading/heading.module.css, packages/storybook/src/components/technicalSpecification/classModule.module.css
Latest changes did mess up with alignement.
This fix back to:
=> fix(doc): prevent heading spacing with hidden elements

packages/ods-react/src/components/button/src/components/button/Button.tsx, packages/ods-react/src/components/spinner/src/components/spinner/Spinner.tsx, packages/ods-react/src/components/spinner/src/components/spinner/spinner.module.scss
Fix semantic issue when used inside `button`
=> refactor(spinner): use span instead of div

packages/ods-react/src/components/select/src/components/select/Select.tsx, packages/ods-react/src/components/select/src/dev.stories.tsx, packages/storybook/stories/components/select/select.stories.tsx
Useful for example for the phone-number flag select, where the control is smaller than the content.
=> feat(select): add fitControlWidth prop
